name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install NPM Dependencies
        run: npm ci
      - name: Lint
        run: ./task lint
        
  shadowbox:
    name: Shadowbox
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Shadowbox Debug Build
        run: ./task shadowbox:build

      - name: Shadowbox Unit Test
        run: ./task shadowbox:test

      - name: Shadowbox Integration Test
        run: ./task shadowbox:integration_test

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
